### ISSUE TITLE
O botão "sobre mim" não funciona

### ISSUE THREAD

**Issue by arandajoao** [marquesgabriel/marquesgabriel.github.io#1]
Quando é pressionado o botão "Sobre mim" o website não redireciona para nenhum lugar.
![image](https://user-images.githubusercontent.com/25693876/27654260-0cc1bb82-5c18-11e7-8d55-19a135e8c13e.png)

**Comment by marquesgabriel** [comment]
Olpa, muito obrigado pelo seu relato. Coloquei esta falha na lista de afazeres. Desde já agradeço!

**Comment by marquesgabriel** [comment]
Meu caro @arandajoao. acabei de enviar um commit ao master, verifique se agora o botão cumpre algo. Até
